---
swagger: "2.0"
info:
  description: "This is a send email API"
  version: "1.0.0"
  title: "Send Email API"
  contact:
    email: "adriaan.botha@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/v1"
schemes:
  - "http"
  - "https"
paths:
  /sendmail:
    post:
      tags:
        - "public"
      summary: "send an email"
      description: "Sends an email with Mailgun or Sendgrid"
      operationId: "sendMail"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "emailBody"
          description: "Email body to send"
          required: false
          schema:
            $ref: "#/definitions/EmailBody"
      responses:
        "200":
          description: "mail successfully sent"
        "202":
          description: "mail successfully sent"
        "400":
          description: "invalid input, object invalid"
      x-swagger-router-controller: "Public"
definitions:
  EmailBody:
    type: "object"
    required:
      - "from"
      - "to"
      - "subject"
      - "text"
    properties:
      from:
        type: "string"
      to:
        type: "string"
      cc:
        type: "string"
      bcc:
        type: "string"
      subject:
        type: "string"
      text:
        type: "string"
      html:
        type: "string"
    example:
      to: "Your name <yourname@email.org>"
      from: "bosotter@protonmail.com"
      cc:
        "Someone CC <someoneCC@example.org>"
      bcc:
        "Soeone BCC <someoneBCC@example.org>"
      subject: "Test Email"
      html: "<p>This is a test email from Sendgrid or MailGun</p>"
      text: "This is a test email from Sendgrid or MailGun"
